app_job_set_result:
    path:   /api/v1/job/result/{jobId}
    methods: [PUT]
    defaults:
        _controller: AppBundle:Job:setResult

app_job_create:
    path:   /api/v1/job/{jobName}
    methods: [POST]
    defaults:
        _controller: AppBundle:Job:create

app_job_retrieve:
    path:   /api/v1/job/{id}
    methods: [GET]
    defaults:
        _controller: AppBundle:Job:retrieve